import Head from "next/head";
import Image from "next/image";
import clientPromise from "../lib/mongo";
import { InferGetServerSidePropsType } from "next";
//import PixiShootingStars from "../components/pixi/pixiShootingStars";
import Snowfall from "react-snowfall";
import postcardImgSrc from "../public/img/postcard.png"
import { MouseEventHandler } from "react";
import Link from "next/link";

export default function Home() {

    return (
        <>
            <Head>
                <title>¡Feliz año 2023! 🌟</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="absolute w-full h-full -z-50">
                {/*<PixiShootingStars />*/}
            </div>
            <Snowfall snowflakeCount={100} color="#dcfce7" speed={[0.5, 8]} wind={[-0.5, 3]} />
            <main className="lg:p-24 p-12 flex justify-center items-center flex-col bg-center bg-[url(/img/bgmain.png)] min-h-screen">
                <h1 className="text-justify lg:text-8xl text-4xl font-christmas">
                    El muro de los deseos
                </h1>
                <div className="py-8 flex lg:flex-row flex-col items-center gap-16">
                    <div className="whitespace-pre-line">
                        Con esta pequeña página web, aprovecho para desearte un feliz Año Nuevo, a la vez que te invito a participar en ella.
                        
                        La he llamado <span className="font-bold">"El muro de los deseos"</span>, y puedes crear tu propia postal para colgarla y difundirla a todos los visitantes de la página.

                        Así, todos juntos podemos crear una red de deseos para conocerlos... ¡y conocernos!
                    </div>
                    <Image src={postcardImgSrc} alt="Postcard image" priority/>
                </div>
                <div>
                    <Link href="postcardWall" passHref>
                        <button className="bg-gradient-to-b from-green-500 to-green-700 py-2 px-3 text-sm font-bold flex justify-center items-center gap-2 rounded-full shadow-lg hover:scale-105 transition-transform duration-150">
                            <p className="text-white text-sm font-bold drop-shadow-lg">Ir al muro</p>
                        </button>
                    </Link>
                </div>
                    
            </main>
        </>
    );
}
