import Head from "next/head";
import Image from "next/image";
import clientPromise from "../lib/mongo";
import { InferGetServerSidePropsType } from "next";
//import PixiShootingStars from "../components/pixi/pixiShootingStars";
import Snowfall from "react-snowfall";
import postcardImgSrc from "../public/img/postcard.png"
import { MouseEventHandler } from "react";
import Link from "next/link";

export async function getServerSideProps(context: any) {
    try {
        await clientPromise;
        // `await clientPromise` will use the default database passed in the MONGODB_URI
        // However you can use another database (e.g. myDatabase) by replacing the `await clientPromise` with the following code:
        //
        // `const client = await clientPromise`
        // `const db = client.db("myDatabase")`
        //
        // Then you can execute queries against your database like so:
        // db.find({}) or any of the MongoDB Node Driver commands

        return {
            props: { isConnected: true },
        };
    } catch (e) {
        console.error(e);
        return {
            props: { isConnected: false },
        };
    }
}

export default function Home({
    isConnected,
}: InferGetServerSidePropsType<typeof getServerSideProps>) {

    return (
        <>
            <Head>
                <title>¡Feliz año 2023! 🌟</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="absolute w-full h-full -z-50">
                {/*<PixiShootingStars />*/}
            </div>
            <Snowfall snowflakeCount={100} color="#dcfce7" speed={[0.5, 8]} wind={[-0.5, 3]} />
            <main className="lg:p-18 flex justify-center items-center flex-col bg-center bg-[url(/img/bgmain.png)] min-h-screen">
                <h1 className="text-justify text-8xl font-christmas">
                    El muro de los deseos
                </h1>
                <div className="py-8 flex lg:flex-row flex-col align-center gap-16">
                    <div>
                        Texto texto Texto texto Texto texto Texto texto Texto texto Texto texto Texto texto 
                    </div>
                    <Image src={postcardImgSrc} alt="Postcard image" priority/>
                </div>
                <div>
                    <Link href="postcardWall" passHref>
                        <button className="p-3 bg-green-100 rounded-md shadow-lg shadow-green-300/40 transition ease-in-out delay-150 hover:scale-110 hover:bg-green-200 duration-300">
                            <p className="text-green-800 text-sm font-bold drop-shadow-lg">Ir al muro</p>
                        </button>
                    </Link>
                </div>
                    
            </main>
        </>
    );
}
